Update CRAD.Rd
vlyubchich/funtimes pull request #5
Opened 2017-11-28 06:47 UTC by DataMining-ClusteringAnalysis

2017-11-28 16:17 UTC, vlyubchich requested changes
Please, see 2 comments.

2017-11-28 16:17 UTC, vlyubchich commented on funtimes/man/CRAD.Rd
> +crad(X, Nbin, StepSize, Rcov = FALSE)
Still doesn't match the code. Can you just use copy-paste from code?

2017-11-28 16:17 UTC, vlyubchich commented on funtimes/man/CRAD.Rd
> +\item{Rcov}{a robust covariance matrix estimator, Minimum Covariance Determinant (MCD), will be used when \code{Rcov = FALSE} (a default option), or the sample covariance matrix \code{cov(X)}.}
Should be reverse, imho. If 'Rcov' means robust estimation, then when it is TRUE, then the robust estimator is applied.

2017-11-29 22:00 UTC, DataMining-ClusteringAnalysis commented
Hi Slava, Thanks for pointing it out. I just updated the description. What do you think this time?

2017-12-01 01:12 UTC, merged